### ISSUE TITLE
sqlite3.ProgrammingError: Recursive use of cursors not allowed

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/strategy-trial#165]
При добавлении посылки получаю:
`127.0.0.1 - - [05/May/2019 17:01:49] "POST /problemset/2 HTTP/1.1" 200 -
[2019-05-05 17:01:51,490] ERROR in app: Exception on /submissions [GET]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tii/Works/Prog/strategy-trial/app/routes/logged_in.py", line 32, in submissions
    mainChanger.applyChange(request)
  File "/home/tii/Works/Prog/strategy-trial/app/forRoutes/mainChanger.py", line 5, in applyChange
    Info = info()
  File "/home/tii/Works/Prog/strategy-trial/app/forRoutes/info.py", line 36, in info
    user = storage.getUser(id)
  File "/home/tii/Works/Prog/strategy-trial/server/storage.py", line 39, in getUser
    return structures.getUser(self.cursor, id)
  File "/home/tii/Works/Prog/strategy-trial/server/structures.py", line 108, in getUser
    lst = getFromDatabase(cursor, 'users', id)
  File "/home/tii/Works/Prog/strategy-trial/server/structures.py", line 46, in getFromDatabase
    cursor.execute('SELECT * FROM ' + tableName + ' WHERE id=?', [id])
sqlite3.ProgrammingError: Recursive use of cursors not allowed.`

**Comment by alexdany657** [comment]
Может быть у меня в игре косяк, но я не уверен

**Comment by cookiedoth** [comment]
я уже несколько раз видел подобную ошибку, но пока не понимаю когда она возникает

**Comment by cookiedoth** [comment]
возможно несколько тредов пытаются одновременно взаимодействовать с базой данных

**Comment by cookiedoth** [comment]
у тебя всегда происходит эта ошибка?

**Comment by alexdany657** [comment]
Нет, не всегда
Случайно почти на всех страницах(закономерности не вижу, это в моей игре)

**Comment by cookiedoth** [comment]
https://stackoverflow.com/questions/26629080/python-and-sqlite3-programmingerror-recursive-use-of-cursors-not-allowed/26630550

**Comment by cookiedoth** [comment]
Есть такая идея

**Comment by cookiedoth** [comment]
Можно делать lock тредов, как здесь написано, запихнуть это в отдельную функция и выполнять вместо cursor.execute

**Comment by alexdany657** [comment]
Давай так
