### ISSUE TITLE
bugs: logs

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/strategy-trial#175]
[2019-05-05 16:41:22,218] ERROR in app: Exception on /problemset/2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions\[rule.endpoint\]\(**req.view_args\)
  File "/home/tii/Works/Prog/strategy-trial/app/routes/all.py", line 38, in problemset_id
    message = Upload(userId, problemId, form)
  File "/home/tii/Works/Prog/strategy-trial/app/forRoutes/upload.py", line 14, in Upload
    addSubmission(userId, problemId, readFile('upload.py'))
  File "/home/tii/Works/Prog/strategy-trial/server/useCasesAPI.py", line 18, in addSubmission
    storage.saveUser(user)
  File "/home/tii/Works/Prog/strategy-trial/server/storage.py", line 61, in saveUser
    user.save(self.cursor)
  File "/home/tii/Works/Prog/strategy-trial/server/structures.py", line 93, in save
    saveList(cursor, 'users', self.getList())
  File "/home/tii/Works/Prog/strategy-trial/server/structures.py", line 41, in saveList
    cursor.execute('DELETE FROM ' + tableName + ' WHERE id=?', [lst[0]])
sqlite3.ProgrammingError: Recursive use of cursors not allowed.
127.0.0.1 - - [05/May/2019 16:41:22] "POST /problemset/2 HTTP/1.1" 500 -

-------------------

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions\[rule.endpoint\]\(**req.view_args\)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/routes/all.py", line 35, in problemset_id
    success, paths, problem, subList, tourList = problemsetId(strId)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/forRoutes/problemsetId.py", line 18, in problemsetId
    problem = storage.getProblem(probId)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/storage.py", line 46, in getProblem
    return structures.getProblem(self.cursor, id)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/structures.py", line 196, in getProblem
    return problemFromList(lst)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/structures.py", line 189, in problemFromList
    return Problem(lst[0], Rules(lst[1], json.loads(lst[2]), json.loads(lst[3]), lst[4]),
IndexError: tuple index out of range

----------------------

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions\[rule.endpoint\]\(**req.view_args\)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/routes/all.py", line 35, in problemset_id
    success, paths, problem, subList, tourList = problemsetId(strId)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/forRoutes/problemsetId.py", line 18, in problemsetId
    problem = storage.getProblem(probId)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/storage.py", line 46, in getProblem
    return structures.getProblem(self.cursor, id)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/structures.py", line 196, in getProblem
    return problemFromList(lst)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/structures.py", line 189, in problemFromList
    return Problem(lst[0], Rules(lst[1], json.loads(lst[2]), json.loads(lst[3]), lst[4]),
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

---------------------

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions\[rule.endpoint\]\(**req.view_args\)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/routes/all.py", line 40, in problemset_id
    isFileUploaded, message = Upload(userId, problemId, form)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/forRoutes/upload.py", line 14, in Upload
    addSubmission(userId, problemId, readFile('upload.py'))
  File "/home/tii/Works/Prog/testing_st/strategy-trial/server/commonFunctions.py", line 8, in readFile
    data = str(myfile.read())
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 3: invalid continuation byte

--------------------

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions\[rule.endpoint\]\(**req.view_args\)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/routes/all.py", line 145, in test
    return invocationResult.logs.show(probId1, {'info': info(), 'title': title})
  File "problems/0/game.py", line 38, in show
    strId = str(probId), **baseParams
  File "/usr/local/lib64/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib64/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/templates/problems/1/logs.html.j2", line 1, in top-level template code
    {% extends "base.html.j2" %}
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/templates/base.html.j2", line 44, in top-level template code
    {% block content %}{% endblock %}
  File "/home/tii/Works/Prog/testing_st/strategy-trial/app/templates/problems/1/logs.html.j2", line 12, in block "content"
    {% if turns[0][i] == 1 %}
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'turns' is undefined

**Comment by alexdany657** [comment]
То что стало ссылками - self.view_functions\[rule.endpoint\]\(**req.view_args\)
