### ISSUE TITLE
timer

### ISSUE THREAD

**Issue by alexdany657** [m20-sch57/strategy-trial#190]
`Execution of job "update (trigger: interval[0:00:01], next run at: 2019-05-19 18:10:41 MSK)" skipped: maximum number of running instances reached (1)
Job "update (trigger: interval[0:00:01], next run at: 2019-05-19 18:10:42 MSK)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/tii/Works/Prog/strategy-trial/server/timer.py", line 12, in update
    if (tourTime != -1 and tourTime <= time):
TypeError: '<=' not supported between instances of 'NoneType' and 'int'`
Я запустил одновременно три турнира.

**Comment by alexdany657** [comment]
Баг вылетает не всегда.
Условия не понял.
Кстати, когда оставлены заявки на три турнира тестирование происходит медленнее(где-то в 3 раза)

**Comment by alexdany657** [comment]
Так все-таки нам лень или нет? (Этот баг виден только на сервере)
